# Generated by Django 3.1.1 on 2020-10-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss', models.FloatField()),
                ('acc', models.FloatField()),
            ],
        ),
    ]
